export const DATE_FORMAT = 'YYYY-MM-DD'
export const MONTH_FORMAT = 'YYYY-MM'
export const YEAR_FORMAT = 'YYYY'

export const CHANGE_FILTER = 'CHANGE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';

export const LOADING_INC_CATEGORIES = 'LOADING_INC_CATEGORIES';
export const SUCCESS_INC_CATEGORIES = 'SUCCESS_INC_CATEGORIES';
export const ERROR_INC_CATEGORIES = 'ERROR_INC_CATEGORIES';
export const SAVE_INC_CATEGORIES = 'SAVE_INC_CATEGORIES';

export const LOADING_EXP_CATEGORIES = 'LOADING_EXP_CATEGORIES';
export const SUCCESS_EXP_CATEGORIES = 'SUCCESS_EXP_CATEGORIES';
export const ERROR_EXP_CATEGORIES = 'ERROR_EXP_CATEGORIES';
export const SAVE_EXP_CATEGORIES = 'SAVE_EXP_CATEGORIES';